---
title: "Regression Analysis"
author: "Claire Zegger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
# install.packages("tidyverse")
# install.packages("modelr")
#install.packages("patchwork")
#install.packages("gtsummary")
#install.packages("gt")
library("tidyverse")
library("modelr")
library("patchwork")
library("gtsummary")
library("gt")
```

## Merged Dataset

important note: mortality rates are only stratified by race and sex from HDMD

```{r datasets}

df <- read.csv("data/HDMD_SDOH_MERGED.csv") # race + sex

```

## Sumary Statistics

```{r summary statistics}
#summary statistics by sex
summary_sex <- df%>%
  filter(Sex != "Overall")%>%
  group_by(Sex)%>%
  filter(Race == "Overall")%>%
  summarise(
    avg_mortality = mean(MortalityRate, na.rm = TRUE),
    med_mortality = median(MortalityRate, na.rm = TRUE),
    var_mortality = var(MortalityRate, na.rm = TRUE))%>%
  gt()%>%
  cols_label(
    avg_mortality = "Average",
    med_mortality = "Median",
    var_mortality = "Variance")%>%
  tab_spanner(
    label = "Mortality Rate (per 100,000)",
    columns = c("avg_mortality", "med_mortality", "var_mortality"))
table_2 <- summary_sex %>%
  fmt_number(
    columns = where(is.numeric),
    decimals = 2
  )
  
```

```{r}
# summary statistics by race
summary_race <- df%>%
  filter(Race != "Overall")%>%
  filter(Sex == "Overall")%>%
  group_by(Race)%>%
  summarise(
    avg_mortality = mean(MortalityRate, na.rm = TRUE),
    med_mortality = median(MortalityRate, na.rm = TRUE),
    var_mortality = var(MortalityRate, na.rm = TRUE))%>%
  gt()%>%
  cols_label(
    avg_mortality = "Average",
    med_mortality = "Median",
    var_mortality = "Variance")%>%
  tab_spanner(
    label = "Mortality Rate (per 100,000)",
    columns = c("avg_mortality", "med_mortality", "var_mortality"))

table_1 <- summary_race %>%
  fmt_number(
    columns = where(is.numeric),
    decimals = 2
  )

table_1
table_2

```

```{r}
# overall summary stats
df%>%
  filter(Race != "Overall")%>%
  filter(Sex != "Overall")%>%
  group_by(Sex)%>%
  drop_na()%>%
  summarise(
    total = length(MortalityRate),
    avg_mortality = mean(MortalityRate, na.rm = TRUE), # mortality is race specific 
    var_mortality = var(MortalityRate, na.rm = TRUE),
    avg_insurance = mean(ACS_PCT_PRIVATE_ANY, na.rm = TRUE)) # insurance is NOT race specific


``` 

``` {r data cleaning}
# filter out na values, selecting variables of interest
filtered_df <- df%>%
  select(County,Race, Sex, MortalityRate, ACS_PCT_PRIVATE_ANY)%>%
  drop_na()


```

## Single Variable Linear Regression: Insurance vs. Mortality
```{r, univariate regression table}

# regression table
overall_df <- filtered_df%>%
  filter(Race == "Overall")%>%
  filter(Sex == "Overall")

lm_univ <- lm(data= overall_df, MortalityRate ~ ACS_PCT_PRIVATE_ANY)
overall_df$pred_univ <- predict(lm_univ)

lm_univ %>%
  tbl_regression(list(ACS_PCT_PRIVATE_ANY = "Health Insurance"))
```

```{r, univariate regression plot, echo = FALSE}
# regression plot
ggplot(data = overall_df)+
  geom_point(aes(x=ACS_PCT_PRIVATE_ANY, y=MortalityRate), size = 2)+
  geom_line(aes(x= ACS_PCT_PRIVATE_ANY, y=pred_univ), color ="red", linewidth = 1.5)+
  ggtitle(str_wrap("Effect of Health Insurance on CVD Mortality in Alabama"))+
  theme(plot.title = element_text(hjust = 0.5, size = 16), 
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14))+
  labs(x = "% of County Population with Private Health Insurance" , 
       y = "Mortalities per 100,000")

```


## Adding Sex as a covariate

```{r insurance and sex regression table}
# regression table
sex_df <- filtered_df%>%
  filter(Race == "Overall")%>%
  filter(Sex != "Overall")%>%
  select(County,Sex,MortalityRate, ACS_PCT_PRIVATE_ANY)

lm_sex <- lm(data = sex_df, MortalityRate ~ ACS_PCT_PRIVATE_ANY+Sex)
sex_df$pred_sex <- predict(lm_sex)
summary(lm_sex)

lm_sex %>%
  tbl_regression(list(ACS_PCT_PRIVATE_ANY = "Health Insurance"), intercept = TRUE)

lm_sex$coefficients
summary(lm_sex)
labels <- c("Intercept", "Health Insurance", "Sex")
beta <- as.numeric(lm_sex$coefficients)

results_sex <- data.frame(labels, beta)

?gt()

gt(results_sex, rowname_col = "labels")

```

```{r regression by insurance and sex plot, echo = FALSE}
# regression plot
ggplot(data=sex_df)+
  geom_point(aes(x=ACS_PCT_PRIVATE_ANY, y=MortalityRate, color = Sex), size = 2)+
  geom_line(aes(x= ACS_PCT_PRIVATE_ANY, y=pred_sex, color = Sex), linewidth =1.5)+
  ggtitle(str_wrap("Effect of Insurance Coverage on Heart Mortality"))+
  labs(x = "% with Private Health Insurance" , 
       y = "Mortalities per 100,000")+
  theme(plot.title = element_text(hjust = 0.5, size = 20), 
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 14))+
    scale_color_manual(
    values = c("Female" = "deepskyblue", 
               "Male" = "red"))

```

## Adding Race and Sex as Covariates

```{r race and sex regression models}

# table of coefficients 
race_df<- filtered_df%>%
  filter(Sex != "Overall")%>%
  filter(Race != "Overall")%>%
  select(County,Sex,MortalityRate, Race, ACS_PCT_PRIVATE_ANY)

lm_full <- lm(data = race_df, MortalityRate ~ ACS_PCT_PRIVATE_ANY+Race+Sex)
race_df$pred <- predict(lm_full)
summary(lm_full)

lm_full %>%
  tbl_regression(list(ACS_PCT_PRIVATE_ANY = "Health Insurance"))

unique(race_df$Race)

# White
race_White <- race_df%>%
  filter(Race == "White")
length(race_White$MortalityRate)

lm_race_White <- lm(data = race_White, MortalityRate ~ ACS_PCT_PRIVATE_ANY+Sex)
race_White$pred <- predict(lm_race_White)
summary(lm_race_White)

# Black
race_Black <- race_df%>%
  filter(Race == "Black")
length(race_Black$MortalityRate)

lm_race_Black <- lm(data = race_Black, MortalityRate ~ ACS_PCT_PRIVATE_ANY+Sex)
race_Black$pred <- predict(lm_race_Black)
summary(lm_race_Black)

## Hispanic
race_Hispanic <- race_df%>%
  filter(Race == "Hispanic")
length(race_Hispanic$MortalityRate) # low sample size

lm_race_Hispanic <- lm(data = race_Hispanic, MortalityRate ~ ACS_PCT_PRIVATE_ANY+Sex)
race_Hispanic$pred <- predict(lm_race_Hispanic)
summary(lm_race_Hispanic)

# Asian and Pacific Islander
race_API <- race_df%>%
  filter(Race == "Asian and Pacific Islander")
length(race_API$MortalityRate) # low sample size

lm_race_API <- lm(data = race_API, MortalityRate ~ ACS_PCT_PRIVATE_ANY+Sex)
race_API$pred <- predict(lm_race_API)
summary(lm_race_API)

# American Indian and Alaskan Native
race_AIAN <- race_df%>%
  filter(Race == "American Indian and Alaskan Native")
length(race_AIAN$MortalityRate) # low sample size

lm_race_AIAN <- lm(data = race_AIAN, MortalityRate ~ ACS_PCT_PRIVATE_ANY+Sex)
race_AIAN$pred <- predict(lm_race_AIAN)
summary(lm_race_AIAN)


```

```{regression tables r}

lm_race_White%>%
  tbl_regression(list(ACS_PCT_PRIVATE_ANY = "Health Insurance"))

lm_race_Hispanic%>%
  tbl_regression(list(ACS_PCT_PRIVATE_ANY = "Health Insurance"))

lm_race_Black%>%
  tbl_regression(list(ACS_PCT_PRIVATE_ANY = "Health Insurance"))

```

```{r White plot, echo = FALSE}

White <- ggplot(data = race_White)+
  geom_point(aes(x=ACS_PCT_PRIVATE_ANY, y=MortalityRate, color = Sex))+
  geom_line(aes(x= ACS_PCT_PRIVATE_ANY, y=pred, color = Sex))+
  ggtitle(str_wrap("White"))+
  ylim(0,1000)+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(x = NULL , 
       y = "Mortalities per 100,000")+
  theme(legend.position = "bottom")+
      scale_color_manual(
    values = c("Female" = "deepskyblue", 
               "Male" = "red"))+
  annotate("text", x = 75, y = 900, hjust = 1.1, vjust = -0.5,
           label = "Beta = -0.28", size = 3, color = "black")

```

```{r Black, echo=FALSE}

Black <- ggplot(data = race_Black)+
  geom_point(aes(x=ACS_PCT_PRIVATE_ANY, y=MortalityRate, color = Sex))+
  geom_line(aes(x= ACS_PCT_PRIVATE_ANY, y=pred, color = Sex))+
  ggtitle(str_wrap("Black"))+
  theme(plot.title = element_text(hjust = 0.5))+
  ylim(0,1000)+
  labs(x = "% with Private Health Insurance" , 
       y = NULL)+
      scale_color_manual(guide = "none",
    values = c("Female" = "deepskyblue", 
               "Male" = "red"))+
  annotate("text", x = 75, y = 900, hjust = 1.1, vjust = -0.5,
           label = "Beta = -4.5***", size = 3, color = "black")


```

```{r Hispanic, echo = FALSE}

Hispanic <- ggplot(data = race_Hispanic)+
  geom_point(aes(x=ACS_PCT_PRIVATE_ANY, y=MortalityRate, color = Sex))+
  geom_line(aes(x= ACS_PCT_PRIVATE_ANY, y=pred, color = Sex))+
  ggtitle("Hispanic")+
  ylim(0,1000)+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(x = NULL, 
       y = NULL)+
      scale_color_manual(guide = "none",
    values = c("Female" = "deepskyblue", 
               "Male" = "red"))+
  annotate("text", x = 75, y = 900, hjust = 1.1, vjust = -0.5,
           label = "Beta = -3.6*", size = 3, color = "black")

```

```{r API, echo = FALSE}

API <- ggplot(data = race_API)+
  geom_point(aes(x=ACS_PCT_PRIVATE_ANY, y=MortalityRate, color = Sex))+
  geom_line(aes(x= ACS_PCT_PRIVATE_ANY, y=pred, color = Sex))+
  ggtitle(str_wrap("API"))+
  labs(x = "% with Private Health Insurance" , 
       y = "Mortalities per 100,000")+
  theme(legend.position = "bottom")

# not enough data to include

```

```{r AIAN, echo = FALSE}

AIAN <- ggplot(data = race_AIAN)+
  geom_point(aes(x=ACS_PCT_PRIVATE_ANY, y=MortalityRate, color = Sex))+
  geom_line(aes(x= ACS_PCT_PRIVATE_ANY, y=pred, color = Sex))+
  ggtitle(str_wrap("AIAN"))+
  labs(x = "% with Private Health Insurance" , 
       y = "CVD Mortalities per 100,000")+
  theme(legend.position = "bottom")

# not enough data to include
print(length(race_AIAN$MortalityRate))


```


```{r race and sex regression plots, echo=FALSE}

White + Black + Hispanic


```




